/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;

import java.sql.*;
import basededatos.conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Thomas
 */
public class registroCiudad extends javax.swing.JFrame {

    String nombreCiudad = "";
    String idCiudad = "";
    int idState = 0;
    conexion conn = new conexion();

    /**
     * Creates new form registroCiudad
     */
    public registroCiudad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idCity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        guardarGabi = new javax.swing.JButton();
        guardarDiana = new javax.swing.JButton();
        guardarLeo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro ciudad");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("ID Ciudad");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nombre");

        guardarGabi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        guardarGabi.setText("Guardar G");
        guardarGabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarGabiActionPerformed(evt);
            }
        });

        guardarDiana.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        guardarDiana.setText("Guardar D");
        guardarDiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDianaActionPerformed(evt);
            }
        });

        guardarLeo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        guardarLeo.setText("Guardar L");
        guardarLeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarLeoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("ID Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(guardarLeo)
                        .addGap(18, 18, 18)
                        .addComponent(guardarDiana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarGabi)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCity)
                    .addComponent(name)
                    .addComponent(idEstado))
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(idEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(guardarGabi)
                    .addComponent(guardarDiana)
                    .addComponent(guardarLeo))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!name.getText().isEmpty() && !idCity.getText().isEmpty() && !idEstado.getText().isEmpty()) {
            nombreCiudad = name.getText();
            idCiudad = idCity.getText();
            idState = Integer.parseInt(idEstado.getText());
            conn.conectar();
            conn.enviarDatosCiudad(nombreCiudad, idCiudad, idState);
        } else {
            //System.out.println("vacio");
            JOptionPane.showMessageDialog(null, "Debe llenar los datos");
        }
        if (conn.status()) {
            System.out.println("Conectado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarDianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDianaActionPerformed
        if (!name.getText().isEmpty() && !idCity.getText().isEmpty() && !idEstado.getText().isEmpty()) {
            nombreCiudad = name.getText();
            idCiudad = idCity.getText();
            idState = Integer.parseInt(idEstado.getText());
            System.out.println("daots ciudad");
            conn.conectarDiana();
            conn.enviarDatosDiana(idCiudad, nombreCiudad, idState);
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar los datos");
        }
        if (conn.status()) {
            System.out.println("Conectado con Diana");
        }

    }//GEN-LAST:event_guardarDianaActionPerformed

    private void guardarLeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarLeoActionPerformed
        if (!name.getText().isEmpty() && !idCity.getText().isEmpty() && !idEstado.getText().isEmpty()) {
            nombreCiudad = name.getText();
            idCiudad = idCity.getText();
            idState = Integer.parseInt(idEstado.getText());
            conn.conectarLeo();
            conn.enviarDatosLeo(idCiudad, nombreCiudad, idState);
        } else {
            //System.out.println("vacio");
            JOptionPane.showMessageDialog(null, "Debe llenar los datos");
        }

        if (conn.status()) {
            System.out.println("Conectado con Leo");
        }

    }//GEN-LAST:event_guardarLeoActionPerformed

    private void guardarGabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarGabiActionPerformed
        if (!name.getText().isEmpty() && !idCity.getText().isEmpty() && !idEstado.getText().isEmpty()) {
            nombreCiudad = name.getText();
            idCiudad = idCity.getText();
            idState = Integer.parseInt(idEstado.getText());
            conn.conectarGabi();
            conn.enviarDatosGabi(idCiudad, nombreCiudad, idState);
        } else {
            //System.out.println("vacio");
            JOptionPane.showMessageDialog(null, "Debe llenar los datos");
        }

        if (conn.status()) {
            System.out.println("Conectado con Gabi");
        }
    }//GEN-LAST:event_guardarGabiActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarDiana;
    private javax.swing.JButton guardarGabi;
    private javax.swing.JButton guardarLeo;
    private javax.swing.JTextField idCity;
    private javax.swing.JTextField idEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

}
